app: photos
service: photos
tenant: hyanmandian

provider:
  name: aws
  runtime: nodejs6.10

stage: dev
region: us-east-1

functions:
  all:
    handler: handler.all
    events:
      - http:
          path: photos
          method: get
          cors: true
  find:
    handler: handler.find
    events:
      - http:
          path: photos/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
